# Generated by Django 3.0.3 on 2020-04-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('body_preview', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NegWordsLM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xyz', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('rank', models.DecimalField(decimal_places=2, max_digits=15)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrievabl.Article')),
            ],
        ),
    ]
