# Generated by Django 3.0.3 on 2020-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrievabl', '0006_auto_20200419_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ndcg',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
